<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- This should be the folder that contains Duckov.exe -->
    <!-- 下面这行里填写你的鸭科夫安装路径，这样编译器就能找到相关的dll文件 -->
    <DuckovPath>E:\Steam\steamapps\common\Escape from Duckov</DuckovPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(DuckovPath)\Duckov_Data\Managed\TeamSoda.*">
      <Private>False</Private>
    </Reference>
    <Reference Include="$(DuckovPath)\Duckov_Data\Managed\ItemStatsSystem.dll">
      <Private>False</Private>
    </Reference>
    <Reference Include="$(DuckovPath)\Duckov_Data\Managed\Unity*">
      <Private>False</Private>
    </Reference>
    <Reference Include="$(DuckovPath)\Duckov_Data\Managed\SodaLocalization.dll">
      <Private>False</Private>
    </Reference>
    <Reference Include="$(DuckovPath)\Duckov_Data\Managed\UniTask*">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.1" />
  </ItemGroup>
</Project>